In [106]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

### 3.3.1 生成数据集

In [107]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

### 3.3.2 读取数据集

In [108]:
batch_size = 10
data_iter = d2l.load_array([features, labels], batch_size)

In [109]:
next(iter(data_iter))

[tensor([[ 1.1488, -0.5100],
         [ 0.1931, -0.0631],
         [-1.4933,  0.9024],
         [ 0.5273,  1.6007],
         [ 0.9766, -0.1138],
         [-0.6890,  0.3016],
         [ 1.4620,  0.1665],
         [-1.4892,  1.1167],
         [ 0.3546, -0.4864],
         [-1.3451, -1.0294]]),
 tensor([[ 8.2480],
         [ 4.7969],
         [-1.8620],
         [-0.2025],
         [ 6.5342],
         [ 1.7883],
         [ 6.5640],
         [-2.5800],
         [ 6.5806],
         [ 5.0094]])]

### 3.3.3 定义模型

In [110]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

### 3.3.4 初始化模型参数

In [111]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [112]:
list(net.parameters())

[Parameter containing:
 tensor([[-0.0015, -0.0109]], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]

### 3.3.5 定义损失函数

In [113]:
loss = nn.MSELoss()

### 3.3.6 定义优化算法

In [114]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

### 3.3.7 训练

In [115]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()

    l = loss(net(features), labels)
    print(f'epoch: {epoch + 1}, loss {l:f}')

epoch: 1, loss 0.000204
epoch: 2, loss 0.000101
epoch: 3, loss 0.000100


In [116]:
w = net[0].weight.data
print(f'w的估计误差: {true_w - w.reshape(true_w.shape)}')

b = net[0].bias.data
print(f'b的误差: {true_b - b}')

w的估计误差: tensor([7.8821e-04, 6.8903e-05])
b的误差: tensor([0.0009])


In [117]:
w, b

(tensor([[ 1.9992, -3.4001]]), tensor([4.1991]))