In [30]:
import torch

In [31]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 3

In [32]:
y.sum().backward(create_graph=True)
x.grad

tensor([ 3., 12., 27.], grad_fn=<CopyBackwards>)

In [ ]:
hessian_rows = []
for g in x.grad:
    # 对一阶梯度的每个分量再求梯度
    g.backward()
    hessian_rows.append(x.grad)

In [29]:
hessian_rows

[(tensor([6., 0., 0.]),),
 (tensor([ 0., 12.,  0.]),),
 (tensor([ 0.,  0., 18.]),)]