In [1]:
import torch
from torch import nn

In [2]:
X = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
])
w = torch.tensor([
    [10.0],
    [20.0],
], requires_grad=True)
b = torch.tensor([5.0], requires_grad=True)

In [3]:
w, w.shape

(tensor([[10.],
         [20.]], requires_grad=True),
 torch.Size([2, 1]))

In [4]:
b, b.shape

(tensor([5.], requires_grad=True), torch.Size([1]))

In [5]:
l = (torch.mm(X, w) + b) ** 2 / 2
l

tensor([[ 1512.5000],
        [ 6612.5000],
        [15312.5000]], grad_fn=<DivBackward0>)

In [6]:
l.mean().backward()

In [7]:
w.grad

tensor([[425.0000],
        [540.0000]])

In [8]:
m = torch.tensor([1.0, 2.0, 101.0], requires_grad=True)
n = torch.tensor([2.0, 3.0, 4.0])

In [9]:
loss = nn.MSELoss()

In [10]:
l = loss(m, n)
l

tensor(3137., grad_fn=<MseLossBackward0>)

In [11]:
l.backward()

In [12]:
m.grad

tensor([-0.6667, -0.6667, 64.6667])

In [13]:
n.mean()

tensor(3.)