### 6.3.1 填充

In [1]:
import torch
from torch import nn

In [9]:
def comp_conv2d(conv2d, X):
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    return Y.reshape(Y.shape[2:])

In [10]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1)
X = torch.rand([8, 8])
comp_conv2d(conv2d, X)

tensor([[-1.8111e-02, -4.1161e-03,  6.4621e-02,  1.3241e-01,  8.2275e-02,
         -5.3197e-02,  1.9893e-02,  2.0365e-01],
        [ 3.0668e-01,  3.0969e-01,  7.2027e-03, -8.0723e-02,  2.3235e-01,
          1.8284e-01,  4.5084e-02, -1.0429e-01],
        [-7.2829e-03, -2.6735e-01,  1.4951e-01,  2.0403e-01,  1.6000e-02,
          2.2304e-01,  1.4568e-01, -6.1336e-03],
        [ 3.2059e-01,  3.0553e-01, -1.3187e-01,  1.2581e-03, -9.4051e-02,
         -2.1398e-02,  1.7822e-01,  1.5949e-01],
        [-1.4726e-02,  1.5931e-01,  1.7578e-01,  1.2344e-01,  1.3463e-01,
         -9.4859e-02, -7.4158e-02,  1.4627e-01],
        [ 2.7406e-01,  1.0560e-01,  1.0742e-01,  1.9136e-01, -1.1057e-01,
         -6.8034e-02,  2.4759e-01,  5.6552e-03],
        [ 2.7915e-01,  3.6576e-02,  4.1548e-03,  1.3270e-01,  2.6897e-01,
          1.0929e-01,  7.0266e-02, -3.3154e-02],
        [ 5.1515e-03, -2.1987e-02,  7.4448e-02,  6.2439e-02,  6.4536e-02,
          4.0757e-02, -5.8443e-02,  1.3135e-04]], grad_fn=<ViewBa

In [12]:
# 使用不用的宽度和高度的核大小
conv2d = nn.Conv2d(1, 1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

torch.Size([8, 8])

### 6.3.2 步幅

In [13]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X)

tensor([[ 0.2897, -0.0893,  0.0335,  0.1313],
        [ 0.1914, -0.0544,  0.3598, -0.1349],
        [ 0.1681, -0.4348,  0.1028, -0.0795],
        [ 0.1536, -0.1488, -0.0667,  0.2816]], grad_fn=<ViewBackward0>)

In [14]:
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X)

tensor([[0.2630, 0.2328],
        [0.5454, 0.2436]], grad_fn=<ViewBackward0>)