### 6.5.1 最大汇聚和平均汇聚

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'mean':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
    return Y

In [4]:
X = torch.tensor([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
], dtype=torch.float32)

In [5]:
pool2d(X, (2, 2), mode='max')

tensor([[4., 5.],
        [7., 8.]])

In [6]:
pool2d(X, (2, 2), mode='mean')

tensor([[2., 3.],
        [5., 6.]])

### 6.5.2 填充和步幅

In [7]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [9]:
pool2d = nn.MaxPool2d(3)
pool2d(X), pool2d(X).shape

(tensor([[[[10.]]]]), torch.Size([1, 1, 1, 1]))

In [10]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

### 6.5.3 多个通道

In [20]:
X1 = torch.cat((X, X + 1), dim=1)  # 总维度不增加
X2 = torch.stack((X, X + 1), dim=1)  # 总维度增加

In [26]:
X1.shape

torch.Size([1, 2, 4, 4])

In [27]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X1)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])