### 2.1.1 入门

In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [7]:
# X = x.reshape(3, 4)
X = x.reshape(-1, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros([2, 3, 4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones([2, 3, 4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn([3, 4])

tensor([[-0.1059,  1.0937,  0.8082, -1.5878],
        [-1.1357,  1.2133, -0.7879,  0.1978],
        [ 0.2730, -0.9719,  1.4653, -0.6327]])

In [14]:
torch.tensor([
    [2, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1],
])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 运算符

In [19]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [22]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [23]:
X = torch.arange(12, dtype=torch.float32).reshape([3, 4])
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1],
])
torch.cat([X, Y], dim=0), torch.cat([X, Y], dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [28]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X.sum()

tensor(66.)

### 2.1.3 广播机制

In [29]:
a = torch.arange(3).reshape([3, 1])
b = torch.arange(2).reshape([1, 2])
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [52]:
# 试试三阶张量的广播机制
j = torch.arange(6).reshape([1, 2, 3])
k = torch.arange(6).reshape([2, 1, 3])
j, k

(tensor([[[0, 1, 2],
          [3, 4, 5]]]),
 tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]))

In [53]:
j + k

tensor([[[ 0,  2,  4],
         [ 3,  5,  7]],

        [[ 3,  5,  7],
         [ 6,  8, 10]]])

### 2.1.4 索引和切片

In [31]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [33]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 节省内存

In [37]:
X, Y

(tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]),
 tensor([[14., 13., 16., 15.],
         [13., 14., 15., 16.],
         [12., 12., 12., 12.]]))

In [36]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [45]:
Z = torch.zeros_like(Y)
print(f'{id(Z) = }')
Z[:] = X + Y
print(f'{id(Z) = }')

id(Z) = 2330043397680
id(Z) = 2330043397680


In [44]:
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 转换为其他Python对象

In [48]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)