### 2.2.1 读取数据集

In [13]:
from pathlib import Path

data_file = Path('./data/house_tiny.csv')
data_file.parent.mkdir(parents=True, exist_ok=True)
data_file.write_text('NumRooms,Alley,Price\nNA,Pave,127500\n2,NA,106000\n4,NA,178100\nNA,NA,140000\n')

73

In [14]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

### 2.2.2 处理缺失值

In [20]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       NaN        True      False
1       2.0       False       True
2       4.0       False       True
3       NaN       False       True

In [22]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

### 2.2.3 转换为张量格式

In [24]:
inputs.values

array([[3.0, True, False],
       [2.0, False, True],
       [4.0, False, True],
       [3.0, False, True]], dtype=object)

In [28]:
import torch

X, y = torch.tensor(inputs.to_numpy(float)), torch.tensor(outputs.to_numpy(float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))