### 5.4.1 不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super(CenteredLayer, self).__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.randn(4, 8))

In [5]:
Y.shape, Y.mean()  # 均值不为0  浮点数误差

(torch.Size([4, 128]), tensor(-1.8626e-09, grad_fn=<MeanBackward0>))

### 5.4.2 带参数的层

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super(MyLinear, self).__init__()

        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.2510,  0.1672, -2.3036],
        [-0.1606,  0.2086,  1.0536],
        [ 0.0312, -2.0401,  0.9567],
        [ 0.5173,  0.4098,  0.1403],
        [-0.1131, -0.1593, -2.1333]], requires_grad=True)

In [14]:
linear(torch.randn(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.randn(2, 64))

tensor([[0.],
        [0.]])