### 5.5.1 加载和保存张量

In [16]:
import torch
from torch import nn
import torch.nn.functional as F
import pickle

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file.pt')

In [3]:
x2 = torch.load('x-file.pt')
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.ones(4)
torch.save([x, y], 'x-files.pt')

In [5]:
x2, y2 = torch.load('x-files.pt')
x2, y2

(tensor([0, 1, 2, 3]), tensor([1., 1., 1., 1.]))

In [6]:
# 储存字典
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict.pt')
mydict2 = torch.load('mydict.pt')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([1., 1., 1., 1.])}

### 5.5.2 加载和保存模型参数

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()

        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

In [8]:
net = MLP()
X = torch.randn([2, 20])
Y = net(X)
Y

tensor([[ 0.0246,  0.2055,  0.4561,  0.4943, -0.1039,  0.2252,  0.2508, -0.0670,
         -0.0480, -0.0041],
        [-0.3388,  0.3189,  0.1527,  0.1285,  0.0395,  0.0009, -0.2403,  0.0364,
          0.1045,  0.0680]], grad_fn=<AddmmBackward0>)

In [9]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.1087,  0.0611, -0.1629,  ..., -0.0890, -0.1250,  0.2162],
                      [-0.1398, -0.0496,  0.0617,  ..., -0.1261,  0.1980, -0.0895],
                      [ 0.1653,  0.0010, -0.1993,  ...,  0.0678, -0.1570, -0.1437],
                      ...,
                      [ 0.1112,  0.1948,  0.1347,  ...,  0.0336,  0.1267,  0.1227],
                      [-0.1513, -0.1396,  0.1959,  ..., -0.0256, -0.1519,  0.0316],
                      [ 0.0324,  0.0143, -0.2199,  ...,  0.1883,  0.0927,  0.1292]])),
             ('hidden.bias',
              tensor([-0.0298, -0.2010, -0.0221,  0.1176, -0.0164,  0.2230, -0.0300,  0.2018,
                       0.0396, -0.1574, -0.1912,  0.0481, -0.0184,  0.1260, -0.1275, -0.1494,
                      -0.1986,  0.0195,  0.1534,  0.1951,  0.1344, -0.1077, -0.2176, -0.0058,
                      -0.2003, -0.0769,  0.1959,  0.2204, -0.1683,  0.0040,  0.1201,  0.0366,
                      -0.2157,

In [10]:
torch.save(net.state_dict(), 'mlp.params.pt')

In [12]:
# 恢复模型参数
clone = MLP()
clone.load_state_dict(torch.load('mlp.params.pt'))
clone.eval()  # 关闭梯度计算和优化参数，只调用forward; 设置为评估模式，保持参数不变，不会更新参数

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [15]:
Y_clone = clone(X)
(Y_clone != Y).sum()

tensor(0)